<a href="https://colab.research.google.com/github/Ms-Noxolo/Team_EN3_Jozi/blob/master/Collaborative_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
#Importing modules
import pandas as pd

In [48]:
# Importing data
train = pd.read_csv('/content/drive/My Drive/Music/train.csv')
test = pd.read_csv('/content/drive/My Drive/Music/test.csv')
movies = pd.read_csv('/content/drive/My Drive/Music/movies.csv')

In [49]:
#Dropping timestamp
train.drop('timestamp',axis=1,inplace=True)

In [50]:
#Reducing the data to can only use the sample
X = train[:1000000]

In [51]:
#Creating a new dataframe of movieId and titles
new = movies.loc[:,['movieId','title']]

In [52]:
#Merging data with titles to can create a pivot_table
X = pd.merge(X,new,on = 'movieId')

In [56]:
#creating a pivot table to can compare the movies to can recommend
table = X[:100000].pivot_table(index=['userId'], columns = ['title'],values = 'rating').fillna(0)

In [57]:
table.head()

title   10 Cloverfield Lane (2016)  ...  You've Got Mail (1998)
userId                              ...
2                              0.0  ...                     0.0
3                              0.0  ...                     0.0
4                              0.0  ...                     0.0
8                              0.0  ...                     0.0
9                              0.0  ...                     0.0

[5 rows x 175 columns]

In [58]:
#creating a similarity table to can compare the distance between movies using pearson correlation
similarity_df = table.corr(method='pearson')

Given that the user has seen a movie and rated it, we are going to recommend him another movie using the rating that he gave to th movie

In [59]:
#Creating a function that sort movies according to their similarity score and return a dataframe of movies he might like
def find_similar(movie_name,rating):
  score = similarity_df[movie_name]*(rating-2.5)
  score = score.sort_values(ascending = False)
  return score

In [68]:
#Finally recommending a new movie
movies=[('Men in Black II (a.k.a. MIIB) (a.k.a. MIB 2) (2002)',4)]
similar_movies = pd.DataFrame()
for movie,rating in movies:
    similar_movies = similar_movies.append(find_similar(movie,rating))
similar_movies.head(10)
pd.DataFrame(similar_movies.sum().sort_values(ascending=False).head(11)).drop(0,axis=1)[1:]

Empty DataFrame
Columns: []
Index: [Harry Potter and the Goblet of Fire (2005), Cars (2006), Orange County (2002), Starsky & Hutch (2004), Star Wars: Episode III - Revenge of the Sith (2005), Spanglish (2004), Sexmission (Seksmisja) (1984), Harry Potter and the Chamber of Secrets (2002), Elf (2003), Deadpool 2 (2018)]